package com.sun.corba.se.PortableActivationIDL;


/**
* com/sun/corba/se/PortableActivationIDL/Repository.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from j:/jenkins/tmp/workspace/build/src/corba/src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Wednesday, January 20, 2021 11:44:15 AM UTC
*/

public interface Repository extends RepositoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Repository
