package org.omg.PortableServer;


/**
* org/omg/PortableServer/IMPLICIT_ACTIVATION_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from j:/jenkins/tmp/workspace/build/src/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Wednesday, January 20, 2021 11:44:16 AM UTC
*/

public interface IMPLICIT_ACTIVATION_POLICY_ID
{

  /**
	 * The value representing IMPLICIT_ACTIVATION_POLICY_ID.
	 */
  public static final int value = (int)(20L);
}
