package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/DISCARDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from j:/jenkins/tmp/workspace/build/src/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Wednesday, January 20, 2021 11:44:16 AM UTC
*/

public interface DISCARDING
{

  /** Object adapter state that causes all requests to be discarded.
   */
  public static final short value = (short)(2);
}
